import { Geist, Geist_Mono } from "next/font/google";
import ClientProvider from "./ClientProvider";
import useAuth from './hooks/authProvider';
import AuthProvider from "./hooks/authProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
